services:
  - type: web
    name: crop-disease-advisor
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromSecret: mongo_uri
